spark {
  app-name = "scala-spark-app"

  iceberg {
    warehouse     = "s3a://warehouse/"
    catalog-type  = "hadoop"
  }
}

minio {
  endpoint          = "http://minio.minio.svc.cluster.local:9000"
  access-key        = "minioadmin"
  secret-key        = "minioadmin123"
  path-style-access = true
}
